services:
  mongodb:
    # Use standard MongoDB image
    image: mongo:8.2.3
    container_name: mongodb
    ports:
      # Map local port 27007 to container port 27017
      - "27007:27017"
    volumes:
      # Persist data in a local folder
      - ./mongodb_data:/data/db
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always  
networks:
  backend:
  
 